### ISSUE TITLE
Fix Image Workflow

### ISSUE THREAD

**Issue by eliflores** [serlo/db-migrations#22]
The [Image](https://github.com/serlo/db-migrations/actions/runs/5392045693/workflow) workflow is currently broken. 

See an example of a failed run [here](https://github.com/serlo/db-migrations/actions/runs/5276746943/jobs/9543876911) and [here](https://github.com/serlo/db-migrations/actions/runs/5392045693/jobs/9789814089).

The error happens on the `yarn push-push` image step:
```
yarn push-image
  shell: /usr/bin/bash -e {0}
  env:
    CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
yarn run v1.22.19
$ ts-node scripts/push-image
/home/runner/work/db-migrations/db-migrations/scripts/push-image.ts:75
    const images = JSON.parse(String(result.stdout))
                        ^
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at shouldBuild (/home/runner/work/db-migrations/db-migrations/scripts/push-image.ts:75:25)
    at buildDockerImage (/home/runner/work/db-migrations/db-migrations/scripts/push-image.ts:50:8)
    at /home/runner/work/db-migrations/db-migrations/scripts/push-image.ts:19:[3](https://github.com/serlo/db-migrations/actions/runs/5392045693/jobs/9789814089#step:7:3)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/db-migrations/db-migrations/node_modules/tslib/tslib.js:16[4](https://github.com/serlo/db-migrations/actions/runs/5392045693/jobs/9789814089#step:7:4):[6](https://github.com/serlo/db-migrations/actions/runs/5392045693/jobs/9789814089#step:7:7)2)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by eliflores** [comment]
This issue is fixed with the upgrade of the version of the `google-github-actions/setup-gcloud` action from 0 to 1 - ref PR: https://github.com/serlo/db-migrations/pull/10.  
✅ run [here](https://github.com/serlo/db-migrations/actions/runs/5392857514/jobs/9806492787).
